# Ruff configuration aligned with CLAUDE.md standards
line-length = 100
target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "D203",  # Incompatible with D211
    "D213",  # Incompatible with D212
    "COM812",  # Can conflict with formatter
    "ISC001",  # Can conflict with formatter
]

[lint.mccabe]
# Maximum cyclomatic complexity
max-complexity = 8

[lint.pydocstyle]
# Use Google-style docstrings
convention = "google"

[lint.pylint]
# Maximum number of branches for function or method
max-branches = 12
# Maximum number of return statements in function or method
max-returns = 6
# Maximum number of positional arguments for function or method
max-positional-args = 5

[lint.per-file-ignores]
# CLI-specific ignores (will be removed by post-gen hook if not CLI project)
"src/**/_cli.py" = [
    "T201",  # Allow print in CLI module
]
"test/**/*.py" = [
    "D",     # No docstrings required in tests
    "S101",  # Allow assert in tests
    "PLR2004",  # Allow magic values in tests
]
"**/conftest.py" = ["D"]  # No docstrings in pytest config

[format]
# Consistent with line-length
line-ending = "lf"
quote-style = "double"