version: 2

updates:
  - package-ecosystem: uv
    cooldown:
      default-days: 7
    directory: /
    groups:
      python:
        patterns:
          - "*"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: daily
